
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: D:/Tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib\\libc.a(lib_a-exit.o): In function `exit':
      exit.c:(.text.exit+0x2c): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/Tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/arm-none-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP开发/1_0_led汇编/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP\u5f00\u53d1/1_0_led\u6c47\u7f16/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-atxwmq"
      binary: "E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP\u5f00\u53d1/1_0_led\u6c47\u7f16/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-atxwmq"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP开发/1_0_led汇编/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-atxwmq
        
        Run Build Command(s):D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/ninja/win/x64/ninja.exe -v cmTC_da9a3 && [1/2] D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj -c "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c"
        Using built-in specs.
        COLLECT_GCC=D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe
        Target: arm-none-eabi
        Configured with: /home/build/work/GCC-5-build/src/gcc/configure --build=i686-linux-gnu --host=i686-w64-mingw32 --target=arm-none-eabi --prefix=/home/build/work/GCC-5-build/install-mingw --libexecdir=/home/build/work/GCC-5-build/install-mingw/lib --infodir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/info --mandir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/man --htmldir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/html --pdfdir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/pdf --enable-languages=c,c++ --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-headers=yes --with-newlib --with-python-dir=share/gcc-arm-none-eabi --with-sysroot=/home/build/work/GCC-5-build/install-mingw/arm-none-eabi --with-libiconv-prefix=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-gmp=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-mpfr=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-mpc=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-isl=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-cloog=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-libelf=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-pkgversion='GNU Tools for ARM Embedded Processors' --with-multilib-list=armv6-m,armv7-m,armv7e-m,armv7-r,armv8-m.base,armv8-m.main
        Thread model: single
        gcc version 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] (GNU Tools for ARM Embedded Processors) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj' '-c'
         d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/cc1.exe -quiet -v -iprefix d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../lib/gcc/arm-none-eabi/5.4.1/ -isysroot d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../arm-none-eabi -D__USES_INITFINI__ D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c -quiet -dumpbase CMakeCCompilerABI.c -auxbase-strip CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj -version -fdiagnostics-color=always -o C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\ccHwkxYE.s
        GNU C11 (GNU Tools for ARM Embedded Processors) version 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] (arm-none-eabi)
        	compiled by GNU C version 4.7.4, GMP version 4.3.2, MPFR version 2.4.2, MPC version 0.8.1
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring duplicate directory "d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/lib/gcc/../../lib/gcc/arm-none-eabi/5.4.1/include"
        ignoring nonexistent directory "d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../arm-none-eabi/home/build/work/GCC-5-build/install-mingw/lib/gcc/arm-none-eabi/5.4.1/../../../../include"
        ignoring duplicate directory "d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/lib/gcc/../../lib/gcc/arm-none-eabi/5.4.1/include-fixed"
        ignoring duplicate directory "d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/lib/gcc/../../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/include"
        ignoring nonexistent directory "d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../arm-none-eabi/usr/include"
        #include "..." search starts here:
        #include <...> search starts here:
         d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../lib/gcc/arm-none-eabi/5.4.1/include
         d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../lib/gcc/arm-none-eabi/5.4.1/include-fixed
         d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/include
        End of search list.
        GNU C11 (GNU Tools for ARM Embedded Processors) version 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] (arm-none-eabi)
        	compiled by GNU C version 4.7.4, GMP version 4.3.2, MPFR version 2.4.2, MPC version 0.8.1
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        Compiler executable checksum: 90e6f7c00b6f60eea64d0b91c3395303
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj' '-c'
         d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/as.exe -v -meabi=5 -o CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\ccHwkxYE.s
        GNU assembler version 2.26.2 (arm-none-eabi) using BFD version (GNU Tools for ARM Embedded Processors) 2.26.2.20160923
        COMPILER_PATH=d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/
        LIBRARY_PATH=d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../arm-none-eabi/lib/
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj' '-c'
        [2/2] cmd.exe /C "cd . && D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe  -v CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj -o cmTC_da9a3.exe -Wl,--out-implib,libcmTC_da9a3.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        FAILED: cmTC_da9a3.exe 
        cmd.exe /C "cd . && D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe  -v CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj -o cmTC_da9a3.exe -Wl,--out-implib,libcmTC_da9a3.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        Using built-in specs.
        COLLECT_GCC=D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe
        COLLECT_LTO_WRAPPER=d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/lto-wrapper.exe
        Target: arm-none-eabi
        Configured with: /home/build/work/GCC-5-build/src/gcc/configure --build=i686-linux-gnu --host=i686-w64-mingw32 --target=arm-none-eabi --prefix=/home/build/work/GCC-5-build/install-mingw --libexecdir=/home/build/work/GCC-5-build/install-mingw/lib --infodir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/info --mandir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/man --htmldir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/html --pdfdir=/home/build/work/GCC-5-build/install-mingw/share/doc/gcc-arm-none-eabi/pdf --enable-languages=c,c++ --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-headers=yes --with-newlib --with-python-dir=share/gcc-arm-none-eabi --with-sysroot=/home/build/work/GCC-5-build/install-mingw/arm-none-eabi --with-libiconv-prefix=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-gmp=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-mpfr=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-mpc=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-isl=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-cloog=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-libelf=/home/build/work/GCC-5-build/build-mingw/host-libs/usr --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-pkgversion='GNU Tools for ARM Embedded Processors' --with-multilib-list=armv6-m,armv7-m,armv7e-m,armv7-r,armv8-m.base,armv8-m.main
        Thread model: single
        gcc version 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] (GNU Tools for ARM Embedded Processors) 
        COMPILER_PATH=d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/
        LIBRARY_PATH=d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib/;d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../arm-none-eabi/lib/
        COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_da9a3.exe'
         d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/collect2.exe -plugin d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/liblto_plugin-0.dll -plugin-opt=d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/lto-wrapper.exe -plugin-opt=-fresolution=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\cc96bGoO.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc --sysroot=d:\\tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\../arm-none-eabi -X -o cmTC_da9a3.exe d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/crti.o d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/crtbegin.o d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib/crt0.o -Ld:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1 -Ld:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc -Ld:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib -Ld:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../arm-none-eabi/lib CMakeFiles/cmTC_da9a3.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_da9a3.dll.a --major-image-version 0 --minor-image-version 0 --start-group -lgcc -lc --end-group d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/crtend.o d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/crtn.o
        d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld.exe: unrecognized option '--major-image-version'
        d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld.exe: use the --help option for usage information
        collect2.exe: error: ld returned 1 exit status
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: D:/Tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/arm-none-eabi-gcc.exe"
    directories:
      source: "E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP\u5f00\u53d1/1_0_led\u6c47\u7f16/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zmhwaz"
      binary: "E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP\u5f00\u53d1/1_0_led\u6c47\u7f16/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zmhwaz"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP开发/1_0_led汇编/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zmhwaz
        
        Run Build Command(s):D:/Tools/Clion/Clion_install/CLion 2023.2.2/bin/ninja/win/x64/ninja.exe -v cmTC_8f464 && [1/2] D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe   -fdiagnostics-color=always -o CMakeFiles/cmTC_8f464.dir/testCCompiler.c.obj -c E:/Hardware/Imx6ull/Workspace/imx6ull_learn/BSP开发/1_0_led汇编/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zmhwaz/testCCompiler.c
        [2/2] cmd.exe /C "cd . && D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe   CMakeFiles/cmTC_8f464.dir/testCCompiler.c.obj -o cmTC_8f464.exe -Wl,--out-implib,libcmTC_8f464.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
        FAILED: cmTC_8f464.exe 
        cmd.exe /C "cd . && D:\\Tools\\gcc-arm-none-eabi\\gcc-arm-none-eabi-install\\bin\\arm-none-eabi-gcc.exe   CMakeFiles/cmTC_8f464.dir/testCCompiler.c.obj -o cmTC_8f464.exe -Wl,--out-implib,libcmTC_8f464.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
        d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld.exe: unrecognized option '--major-image-version'
        d:/tools/gcc-arm-none-eabi/gcc-arm-none-eabi-install/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld.exe: use the --help option for usage information
        collect2.exe: error: ld returned 1 exit status
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
